# -*- coding: utf-8 -*-
#  Gestión de Proyectos Fin de Carrera de la Universidad de La Laguna
#
#    Copyright (C) 2011-2012 Pedro Cabrera <pdrcabrod@gmail.com>
#                            Jesús Torres  <jmtorres@ull.es>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

ISO639_1 = (
    ('aa', u'Afar'),
    ('ab', u'Abjaso (o abjasiano)'),
    ('ae', u'Avéstico'),
    ('af', u'Afrikaans'),
    ('ak', u'Akano'),
    ('am', u'Amárico'),
    ('an', u'Aragonés'),
    ('ar', u'Árabe'),
    ('as', u'Asamés'),
    ('av', u'Avar'),
    ('ay', u'Aimara'),
    ('az', u'Azerí'),
    ('ba', u'Baskir'),
    ('be', u'Bielorruso'),
    ('bg', u'Búlgaro'),
    ('bh', u'Bhojpurí'),
    ('bi', u'Bislama'),
    ('bm', u'Bambara'),
    ('bn', u'Bengalí'),
    ('bo', u'Tibetano'),
    ('br', u'Bretón'),
    ('bs', u'Bosnio'),
    ('ca', u'Catalán'),
    ('ce', u'Checheno'),
    ('ch', u'Chamorro'),
    ('co', u'Corso'),
    ('cr', u'Cree'),
    ('cs', u'Checo'),
    ('cu', u'Eslavo eclesiástico antiguo'),
    ('cv', u'Chuvasio'),
    ('cy', u'Galés'),
    ('da', u'Danés'),
    ('de', u'Alemán'),
    ('dv', u'Maldivo'),
    ('dz', u'Dzongkha'),
    ('ee', u'Ewe'),
    ('el', u'Griego (moderno)'),
    ('en', u'Inglés'),
    ('eo', u'Esperanto'),
    ('es', u'Español'),
    ('et', u'Estonio'),
    ('eu', u'Euskera'),
    ('fa', u'Persa'),
    ('ff', u'Fula'),
    ('fi', u'Finés (o finlandés)'),
    ('fj', u'Fiyiano (o fiyi)'),
    ('fo', u'Feroés'),
    ('fr', u'Francés'),
    ('fy', u'Frisón (o frisio)'),
    ('ga', u'Irlandés (o gaélico)'),
    ('gd', u'Gaélico escocés'),
    ('gl', u'Gallego'),
    ('gn', u'Guaraní'),
    ('gu', u'Guyaratí (o guyaratí)'),
    ('gv', u'Manés (gaélico manés o de Isla de Man)'),
    ('ha', u'Hausa'),
    ('he', u'Hebreo'),
    ('hi', u'Hindi (o hindú)'),
    ('ho', u'Hiri motu'),
    ('hr', u'Croata'),
    ('ht', u'Haitiano'),
    ('hu', u'Húngaro'),
    ('hy', u'Armenio'),
    ('hz', u'Herero'),
    ('ia', u'Interlingua'),
    ('id', u'Indonesio'),
    ('ie', u'Occidental'),
    ('ig', u'Igbo'),
    ('ii', u'Yi de sichuán'),
    ('ik', u'Inupiaq'),
    ('io', u'Ido'),
    ('is', u'Islandés'),
    ('it', u'Italiano'),
    ('iu', u'Inuktitut'),
    ('ja', u'Japonés'),
    ('jv', u'Javanés'),
    ('ka', u'Georgiano'),
    ('kg', u'Kongo'),
    ('ki', u'Kikuyu'),
    ('kj', u'Kuanyama'),
    ('kk', u'Kazajo (o kazajio)'),
    ('kl', u'Groenlandés (o kalaallisut)'),
    ('km', u'Camboyano (o jemer)'),
    ('kn', u'Canarés'),
    ('ko', u'Coreano'),
    ('kr', u'Kanuri'),
    ('ks', u'Cachemiro'),
    ('ku', u'Kurdo'),
    ('kv', u'Komi'),
    ('kw', u'Córnico'),
    ('ky', u'Kirguís'),
    ('la', u'Latín'),
    ('lb', u'Luxemburgués'),
    ('lg', u'Luganda'),
    ('li', u'Limburgués'),
    ('ln', u'Lingala'),
    ('lo', u'Lao'),
    ('lt', u'Lituano'),
    ('lu', u'Luba-katanga'),
    ('lv', u'Letón'),
    ('mg', u'Malgache (o malagasy)'),
    ('mh', u'Marshalés'),
    ('mi', u'Maorí'),
    ('mk', u'Macedonio'),
    ('ml', u'Malayalam'),
    ('mn', u'Mongol'),
    ('mr', u'Maratí'),
    ('ms', u'Malayo'),
    ('mt', u'Maltés'),
    ('my', u'Birmano'),
    ('na', u'Nauruano'),
    ('nb', u'Noruego bokmål'),
    ('nd', u'Ndebele del norte'),
    ('ne', u'Nepalí'),
    ('ng', u'Ndonga'),
    ('nl', u'Neerlandés (u holandés)'),
    ('nn', u'Nynorsk'),
    ('no', u'Noruego'),
    ('nr', u'Ndebele del sur'),
    ('nv', u'Navajo'),
    ('ny', u'Chichewa'),
    ('oc', u'Occitano'),
    ('oj', u'Ojibwa'),
    ('om', u'Oromo'),
    ('or', u'Oriya'),
    ('os', u'Osético'),
    ('pa', u'Panyabí (o penyabi)'),
    ('pi', u'Pali'),
    ('pl', u'Polaco'),
    ('ps', u'Pastú (o pashto)'),
    ('pt', u'Portugués'),
    ('qu', u'Quechua'),
    ('rm', u'Retorrománico'),
    ('rn', u'Kirundi'),
    ('ro', u'Rumano'),
    ('ru', u'Ruso'),
    ('rw', u'Ruandés'),
    ('sa', u'Sánscrito'),
    ('sc', u'Sardo'),
    ('sd', u'Sindhi'),
    ('se', u'Sami septentrional'),
    ('sg', u'Sango'),
    ('sh', u'Serbocroata'),
    ('si', u'Cingalés'),
    ('sk', u'Eslovaco'),
    ('sl', u'Esloveno'),
    ('sm', u'Samoano'),
    ('sn', u'Shona'),
    ('so', u'Somalí'),
    ('sq', u'Albanés'),
    ('sr', u'Serbio'),
    ('ss', u'Suazi (swati o siswati)'),
    ('st', u'Sesotho'),
    ('su', u'Sundanés'),
    ('sv', u'Sueco'),
    ('sw', u'Suajili'),
    ('ta', u'Tamil'),
    ('te', u'Telugú'),
    ('tg', u'tayiko'),
    ('th', u'Tailandés'),
    ('ti', u'Tigriña'),
    ('tk', u'Turcomano'),
    ('tl', u'Tagalo'),
    ('tn', u'Setsuana'),
    ('to', u'Tongano'),
    ('tr', u'Turco'),
    ('ts', u'Tsonga'),
    ('tt', u'Tártaro'),
    ('tw', u'Twi'),
    ('ty', u'Tahitiano'),
    ('ug', u'Uigur'),
    ('uk', u'Ucraniano'),
    ('ur', u'Urdu'),
    ('uz', u'Uzbeko'),
    ('ve', u'Venda'),
    ('vi', u'Vietnamita'),
    ('wl', u'Walisiano'),
    ('vo', u'Volapük'),
    ('wa', u'Valón'),
    ('wo', u'Wolof'),
    ('xh', u'Xhosa'),
    ('yi', u'Yídish (o yiddish)'),
    ('yo', u'Yoruba'),
    ('za', u'Chuan (o zhuang)'),
    ('zh', u'Chino'),
    ('zu', u'Zulú'),
)
